ALTER TABLE users
    ADD COLUMN gender VARCHAR(10) NOT NULL DEFAULT 'MALE';
ALTER TABLE users
    ADD COLUMN birthday VARCHAR(20) NOT NULL DEFAULT '';
ALTER TABLE users
    ADD COLUMN account_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE users RENAME COLUMN verified TO email_verified;